apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: meungnix
spec:
  replicas: 10
  selector:
    matchLabels:
      app: meungnix
  template:
    metadata:
      labels:
        app: meungnix
    spec:
      containers:
        - name: webserver
          image: nginx:1.21.3
          ports:
            - containerPort: 80
